name: Lambdatest

on:
  workflow_dispatch:

permissions: 
       id-token: write
       contents: write
       packages: write
    
jobs:
  FunctionLambda:

    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
#     - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@master
#       with:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
#          aws-region: us-west-2
         
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        
    - name: zip Lambda Function
      run: |
           zip -r9 lambda.zip ./index.js
        
    - name: AWS Lambda Deploy
      run: aws lambda update-function-code --function-name Testlambdafunction --zip-file fileb://lambda.zip
      
#       run: aws lambda update-function-code --function-name Testlambdafunction --region us-west-2 --zip-file fileb://testlambda.zip
#       env:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-west-2
         
#     - name: Install Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
        
#     - name: Install NPM packages
#       run: npm ci

#     - name: Install dependencies
#       run: |
#         npm install
#         npm install react-bootstrap bootstrap
        
#     - name: Build
#       run: npm run build
        
#     - name: Deploy
#       run: |
#          git config --global user.name "${{ runner.name }}"
#          git config --global user.email $user_email
#          git remote set-url origin https://${{secrets.ACTIONS_DEPLOY_ACCESS_TOKEN}}@github.com/${{github.repository}}
#          npm run deploy
#       env:
#          user_email: 'github-actionsPages@users.noreply.github.com'
#          repository: ${{ github.repository }}
